### ISSUE TITLE
Titles not getting rewritten. Same with description.

### ISSUE THREAD

**Issue by Sweely** [paulmassen/grav-plugin-seo#6]
Hi Paul,

Thanks for taking the time to create a plugin like this for the Grav CMS.

Unfortunately it doesn't seem to work for me out of the box.

I do get access to the SEO tab when I edit every page but the changes don't actually get posted.

No matter what I type as my title or description, only the defaults are shown:

`<meta name="description" content="Grav is an easy to use, yet powerful, open source flat-file CMS" />`

I'm using the latest version of the Grav CMS (1.2.4) - is it compatible with your plugin?

/Nabil

**Comment by paulmassen** [comment]
Hi Nabil, 

Thanks for reporting your experience with the plugin.
Actually, most of the skeletons or Grav theme include in their base.html.twig a metadata.html.twig template that outputs the meta description, and most of them also have a line for defining the title tag.

Make sure you followed the installation step, especially this one

> Step 2: If you use a Grav Theme or Skeleton, make sure to remove the <title></title> tags as well as the meta description tag that comes with most of them inside base.html.twig, as the plugin takes care of rendering it.

and try removing the line that include partials/metadata.html.twig and it should work.

Finally, dont forget to take a look instide Configuration > Site: there is a _Site Description_ fields that you should fill in because the plugin will look for this if the fields on the SEO tabs are left empty.

Hope it helps,

Paul

**Comment by lukevhf** [comment]
Hi Paul,
if i try to don't use metadata is impossible to use other tag like
  refresh:   
    keywords: 
    author: 
    robots: 
   Is possible. you think to eliminate description in metadata file ?

**Comment by paulmassen** [comment]
fixed in 2.0.0+ releases
